### PR TITLE
[10.0][MIG] mail_create_partner

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

- [x] The javascript part is ccompleted.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
I think we could merge this with `installable = False` and proceed with the other modules.

**Comment by AaronHForgeFlow** [comment]
Why not leaving the PR opened and putting the label "Work in progress"?

**Comment by MiquelRForgeFlow** [comment]
ok

**Review by AaronHForgeFlow — COMMENTED** [review]
image

**Comment by MiquelRForgeFlow** [comment]
Fixed by https://github.com/Eficent/mailbox_replica/pull/19.

**Review by AaronHForgeFlow — COMMENTED** [review]
The button to create the partner is missing

**Pull request merged**
